apiVersion: v1
kind: Service
metadata:
  name: webapp-stable
spec:
  selector:
    app: webapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-canary
spec:
  selector:
    app: webapp
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
